name: SLinC CI
on:
  pull_request:
  push: 
    branches:
      - "master"


jobs: 
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: coursier/cache-action@v6
      - uses: bleep-build/bleep-setup-action@0.0.1
      - run: bleep fmt --check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: bleep-build/bleep-setup-action@0.0.1
      - run: mkdir reports
      - name: Core tests
        run: bleep test core-tests