name: .github/workflows/main.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '1.19'
- name: Install mill
        run: curl -L -o mill https://github.com/lihaoyi/mill/releases/download/<mill_version>/mill -sSf
      - name: Make mill executable
        run: chmod +x mill

      - name: Run mill command
        run: mill <command>

      - name: Additional steps
        - name: Additional steps
        uses: actions/setup-java@v2
        with:
          java-version: '1.19'
