name: Release
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - name: Get Secrets
      uses: bitwarden/sm-action@v1
      with:
        access_token: ${{ secrets.BW_ACCESS_TOKEN }}
        secrets: |
          e5a2f416-de5c-4f2d-bc09-b060011d760b > USERNAME
          44adbbc1-df7f-432f-8034-b060011d5d94 > PASS
    - name: Get JVMs 
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin'
        java-version: |
          17
          19
    - name: Publish Core 
      run: | 
        ./mill core.publish --sonatypeCreds "$USERNAME:$PASS" --release true 
      env: 
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
    - name: Publish J17 
      run: |
        ./mill j17.publish --sonatypeCreds "$USERNAME:$PASS" --release true 
      env: 
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      
    - name: Publish J19 
      run: ./mill j19.publish --sonatypeCreds "$USERNAME:$PASS" --release true

    - name: Publish Runtime 
      run: ./mill runtime.publish --sonatypeCreds "$USERNAME:$PASS" --release true 
      env: 
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}